import seedData from "./outros/banco-escala-louvor.json";
import { createClient } from "@supabase/supabase-js";

const $ = (s, root = document) => root.querySelector(s);
const $$ = (s, root = document) => [...root.querySelectorAll(s)];
const STORAGE = "pib-maracaju-escala-v1";
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || import.meta.env.VITE_SUPABASE_ANON_KEY;
const SUPABASE_BUCKET = import.meta.env.VITE_SUPABASE_BUCKET || "arquivos-louvor";
const supabase = SUPABASE_URL && SUPABASE_KEY ? createClient(SUPABASE_URL,SUPABASE_KEY) : null;
const FUNCOES = ["Dirigente","Vocal feminino","Vocal masculino","Violão","Guitarra","Baixo","Teclado","Bateria","Piano","Órgão","Mídia","Som","Mesa de corte","Câmera 1","Câmera 2"];
const MOMENTOS = ["Abertura","Louvor","Oferta","Ceia","Batismo"];
const CULTOS = ["Culto da Família (dom 19h)","Culto de Oração (qua 19h)","EBD (dom 9h)","Culto Jovem (sáb 18h)","Evento especial"];
const ICONS = {"Dirigente":"♟","Vocal feminino":"🎙","Vocal masculino":"🎙","Violão":"🎸","Guitarra":"🎸","Baixo":"🎸","Teclado":"🎹","Bateria":"🥁","Piano":"🎹","Órgão":"🎹","Mídia":"▶","Som":"🎚","Mesa de corte":"🎛","Câmera 1":"📹","Câmera 2":"📹"};
const POSITIONS = {"Bateria":[18,10],"Guitarra":[13,21],"Violão":[29,21],"Baixo":[43,21],"Teclado":[61,21],"Órgão":[91,12],"Piano":[91,22],"Dirigente":[50,31],"Câmera 2":[12,45],"Câmera 1":[88,45],"Som":[25,87],"Mesa de corte":[50,87],"Mídia":[75,87]};
const TEAM = {"Dirigente":"lideranca","Vocal feminino":"vocais","Vocal masculino":"vocais","Violão":"instrumentos","Guitarra":"instrumentos","Baixo":"instrumentos","Teclado":"instrumentos","Bateria":"instrumentos","Piano":"instrumentos","Órgão":"instrumentos","Câmera 1":"transmissao","Câmera 2":"transmissao","Mesa de corte":"transmissao","Som":"audio","Mídia":"midia"};
const VOCAL_LIMITS = {"Vocal masculino":2,"Vocal feminino":3};
const TEAM_COLOR = {instrumentos:"var(--instrumentos)",vocais:"var(--vocais)",lideranca:"var(--lideranca)",transmissao:"var(--transmissao)",audio:"var(--audio)",midia:"var(--midia)"};
const TEAM_LABEL = {instrumentos:"Instrumentos",vocais:"Vocais",lideranca:"Liderança",transmissao:"Transmissão",audio:"Áudio",midia:"Mídia"};
const DEFAULT_AVATAR = Object.freeze({pele:"#f0bd89",cabelo:"#171817"});
const roleColor = f => f==="Vocal feminino" ? "#b83f7a" : f==="Vocal masculino" ? "#405ca8" : teamColor(f);
const state = { db:null, screen:"escala", selected:null, calendar:false, calendarDate:new Date(), query:"", drawer:false, sheet:null, modal:null, editorMode:"mapa", editingScale:null, canvasRaf:null, storageSession:null, audio:null, cloudLoading:false, cloudReady:false, cloudError:"", syncing:false };

const esc = v => String(v ?? "").replace(/[&<>'"]/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const uid = () => Math.random().toString(36).slice(2,10);
const parseDate = s => new Date(`${s}T12:00:00`);
const iso = d => `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;
const fmt = (s, opts={day:"2-digit",month:"long",year:"numeric"}) => parseDate(s).toLocaleDateString("pt-BR",opts);
const shortName = n => n.split(" ")[0];
const member = id => state.db.membros.find(m=>m.id===id);
const music = id => state.db.musicas.find(m=>m.id===id);
const teamColor = f => TEAM_COLOR[TEAM[f]||"instrumentos"];
const safeUrl = value => { try { const url=new URL(String(value||""),location.href); return ["http:","https:"].includes(url.protocol)?url.href:""; } catch { return ""; } };
const isLeader = () => Boolean(state.storageSession);
function requestLeaderAccess(){state.drawer=false;state.sheet=null;state.leaderLogin=true;render()}
function requireLeader(){if(isLeader())return true;requestLeaderAccess();toast("Entre como líder para alterar as escalas");return false}
const save = () => { try { localStorage.setItem(STORAGE, JSON.stringify(state.db)); return true; } catch { toast("Não foi possível salvar neste dispositivo"); return false; } };
function toast(msg){ const el=$("#toast"); el.textContent=msg; el.classList.add("show"); clearTimeout(toast.t); toast.t=setTimeout(()=>el.classList.remove("show"),2600); }
function activeScale(){ return state.db.escalas.find(e=>e.id===state.selected) || state.db.escalas[0]; }
function nearestScale(){ const today=iso(new Date()); return [...state.db.escalas].sort((a,b)=>a.data.localeCompare(b.data)).find(e=>e.data>=today) || [...state.db.escalas].sort((a,b)=>b.data.localeCompare(a.data))[0]; }
function occurrences(type,id){ const rows=state.db.escalas.filter(e => type==="m" ? e.equipe.some(x=>x.id===id) : e.repertorio.some(x=>x.musicaId===id)).sort((a,b)=>b.data.localeCompare(a.data)); return {count:rows.length,last:rows[0]?.data}; }

function groupBy(items,key){return items.reduce((map,item)=>{const value=item[key];(map[value]||=[]).push(item);return map},{})}
function resourceName(value){return String(value||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/\.[^.]+$/,"").replace(/[^a-z0-9]+/g," ").trim()}
function containsResourcePhrase(text,phrase){return phrase.length>=5&&` ${text} `.includes(` ${phrase} `)}
async function attachStorageLinks(songs){
  if(!supabase||!songs.length)return;
  try{
    const [pdfResult,mp3Result]=await Promise.all([
      supabase.storage.from(SUPABASE_BUCKET).list("cifras",{limit:1000,sortBy:{column:"name",order:"asc"}}),
      supabase.storage.from(SUPABASE_BUCKET).list("vs",{limit:1000,sortBy:{column:"name",order:"asc"}})
    ]);
    if(pdfResult.error||mp3Result.error)return;
    const match=(song,files,folder)=>{const title=resourceName(song.titulo),hymnCode=resourceName(`${song.numero||""}${song.hinario||""}`).replaceAll(" ","");const candidates=(files||[]).filter(file=>{const name=resourceName(file.name),compact=name.replaceAll(" ","");return containsResourcePhrase(name,title)||containsResourcePhrase(title,name)||(hymnCode.length>=3&&compact.startsWith(hymnCode))});if(candidates.length!==1)return "";return supabase.storage.from(SUPABASE_BUCKET).getPublicUrl(`${folder}/${candidates[0].name}`).data.publicUrl};
    songs.forEach(song=>{if(!song.cifra)song.cifra=match(song,pdfResult.data,"cifras");if(!song.vs)song.vs=match(song,mp3Result.data,"vs")});
  }catch{}
}
async function loadCloudData(){
  if(!supabase)return false;
  state.cloudLoading=true;state.cloudError="";
  try{
    const results=await Promise.all([
      supabase.from("membros").select("id,nome,whatsapp,avatar,ativo").eq("ativo",true),
      supabase.from("membro_funcoes").select("membro_id,funcao,ordem").order("ordem"),
      supabase.from("musicas").select("id,tipo,hinario,numero,titulo,tom_padrao,youtube_url,cifra_url,vs_url,ativo").eq("ativo",true),
      supabase.from("escalas").select("id,data,culto,saudacao,ensaio,observacoes").order("data"),
      supabase.from("escala_equipe").select("escala_id,membro_id,funcao,ordem").order("ordem"),
      supabase.from("escala_repertorio").select("id,escala_id,musica_id,tom,momento,ordem").order("ordem")
    ]);
    const failed=results.find(result=>result.error);if(failed)throw failed.error;
    const [membersResult,rolesResult,songsResult,scalesResult,teamResult,repertoireResult]=results;
    const roles=groupBy(rolesResult.data,"membro_id"),team=groupBy(teamResult.data,"escala_id"),repertoire=groupBy(repertoireResult.data,"escala_id");
    state.db={
      membros:membersResult.data.map(m=>({id:m.id,nome:m.nome,whatsapp:m.whatsapp||"",avatar:m.avatar||{},funcoes:(roles[m.id]||[]).sort((a,b)=>a.ordem-b.ordem).map(r=>r.funcao)})),
      musicas:songsResult.data.map(m=>({id:m.id,tipo:m.tipo,hinario:m.hinario||"",numero:m.numero||"",titulo:m.titulo,tom:m.tom_padrao||"",youtube:m.youtube_url||"",cifra:m.cifra_url||"",vs:m.vs_url||""})),
      escalas:scalesResult.data.map(s=>({id:s.id,data:s.data,culto:s.culto,saudacao:s.saudacao||"Olá!",ensaio:s.ensaio||"",obs:s.observacoes||"",equipe:(team[s.id]||[]).sort((a,b)=>a.ordem-b.ordem).map(x=>({id:x.membro_id,funcao:x.funcao})),repertorio:(repertoire[s.id]||[]).sort((a,b)=>a.ordem-b.ordem).map(x=>({chave:x.id,musicaId:x.musica_id,tom:x.tom||"",momento:x.momento||"Louvor"}))}))
    };
    await attachStorageLinks(state.db.musicas);state.cloudReady=true;save();return true;
  }catch(error){state.cloudReady=false;state.cloudError=error?.message||"Não foi possível carregar o banco de dados.";return false}
  finally{state.cloudLoading=false}
}

async function init(){
  try { state.db=JSON.parse(localStorage.getItem(STORAGE)) || structuredClone(seedData); }
  catch { state.db=structuredClone(seedData); }
  state.db={membros:Array.isArray(state.db?.membros)?state.db.membros:[],musicas:Array.isArray(state.db?.musicas)?state.db.musicas:[],escalas:Array.isArray(state.db?.escalas)?state.db.escalas:[]};
  const mergeSeed=(current,seed)=>{const existing=new Map(current.map(x=>[x.id,x]));return [...current,...seed.filter(x=>!existing.has(x.id)).map(x=>structuredClone(x))]};
  state.db.membros=mergeSeed(state.db.membros,seedData.membros);state.db.musicas=mergeSeed(state.db.musicas,seedData.musicas);
  const seedSongs=new Map(seedData.musicas.map(m=>[m.id,m]));state.db.musicas.forEach(m=>{const source=seedSongs.get(m.id);if(source?.youtube&&!m.youtube)m.youtube=source.youtube});
  state.db.membros.forEach(m=>{ m.funcoes=[...new Set(m.funcoes.map(f=>f==="Transmissão"?"Mesa de corte":f).filter(f=>f!=="Percussão"))]; m.avatar=avatarSettings(m); });
  state.db.escalas.forEach(e=>{const migrated=e.equipe.filter(x=>x.funcao!=="Percussão").map(x=>({...x,funcao:x.funcao==="Transmissão"?"Mesa de corte":x.funcao}));e.equipe=[...new Map(migrated.map(x=>[`${x.id}:${x.funcao}`,x])).values()];if(!e.saudacao||/^bom+m*\s*dia+a*$/i.test(e.saudacao.trim()))e.saudacao="Olá!"}); state.db.escalas.sort((a,b)=>a.data.localeCompare(b.data));
  save();
  if(supabase){try{const {data}=await supabase.auth.getSession();state.storageSession=data.session;await loadCloudData()}catch{state.storageSession=null}}
  state.selected=nearestScale()?.id; const a=activeScale(); if(a) state.calendarDate=parseDate(a.data);
  document.addEventListener("keydown",e=>{if(e.key!=="Escape")return;if(state.modal){state.modal=null;render()}else if(state.sheet){state.sheet=null;render()}else if(state.drawer){state.drawer=false;render()}});
  render();
}

function shell(content){
  return `<div class="app-shell">
    <header class="topbar"><button class="icon-btn" data-action="drawer" aria-label="Abrir menu">☰</button><div class="brand-title"><strong>ESCALA LOUVOR</strong><span>Primeira Igreja Batista de Maracaju</span></div><button class="avatar-button ${isLeader()?'leader-active':''}" data-action="${isLeader()?'drawer':'leader-login'}" aria-label="${isLeader()?'Área do líder':'Entrar como líder'}">${isLeader()?'LÍD':'PIB'}</button></header>
    <main class="main">${content}</main>${audioDock()}${bottomNav()}${drawer()}${sheet()}${modal()}</div>`;
}
function authScreen(){return `<div class="auth-screen"><section class="auth-card"><div class="auth-brand"><span>♫</span><div><strong>ESCALA LOUVOR</strong><small>Primeira Igreja Batista de Maracaju</small></div></div><div class="auth-copy"><span class="eyebrow">Área dos líderes</span><h1>Entrar para editar</h1><p>A visualização é pública. Use a conta de um líder do ministério apenas para alterar escalas e cadastros.</p></div><form data-app-login><div class="field"><label>E-mail</label><input name="email" type="email" autocomplete="email" required autofocus placeholder="seuemail@exemplo.com"></div><div class="field"><label>Senha</label><input name="password" type="password" autocomplete="current-password" required placeholder="Sua senha"></div><small class="auth-error" data-app-auth-status></small><button class="btn btn-primary btn-wide">Entrar como líder</button></form><button class="btn btn-light btn-wide" data-action="close-leader-login">Continuar somente visualizando</button><small class="auth-security">🔒 Somente contas autorizadas podem salvar alterações</small></section></div>`}
function cloudErrorScreen(){return `<div class="auth-screen"><section class="auth-card"><div class="auth-brand"><span>!</span><div><strong>Não foi possível carregar</strong><small>Conexão com o banco de dados</small></div></div><p class="cloud-error-text">${esc(state.cloudError)}</p><button class="btn btn-primary btn-wide" data-action="retry-cloud">Tentar novamente</button><button class="btn btn-light btn-wide" data-action="logout">Sair da conta</button></section></div>`}
function audioDock(){if(!state.audio)return "";const url=safeUrl(state.audio.url);if(!url)return "";return `<aside class="audio-dock" aria-label="Reprodutor de VS"><div class="audio-meta"><span>♪</span><div><small>VS em reprodução</small><strong>${esc(state.audio.title)}</strong></div></div><audio src="${esc(url)}" controls autoplay></audio><a class="audio-download" href="${esc(url)}" target="_blank" rel="noopener noreferrer" download="${esc(fileName(state.audio.title,'mp3'))}" aria-label="Baixar VS">↓</a><button class="audio-close" data-action="close-audio" aria-label="Fechar reprodutor">×</button></aside>`}
function bottomNav(){ return `<nav class="bottom-nav" aria-label="Navegação principal">${[["escala","⌂","Escala"],["agenda","▣","Agenda"],["repertorio","♫","Repertório"],["equipe","♙","Equipe"]].map(([id,i,l])=>`<button class="tab ${state.screen===id?'active':''}" data-nav="${id}"><span class="tab-icon">${i}</span>${l}</button>`).join("")}</nav>`; }
function drawer(){ const groups=[
  ["Ir para",[["escala","⌂","Escala"],["agenda","▣","Agenda"],["repertorio","♫","Repertório"],["equipe","♙","Equipe"]]],
  ["Este culto",[["escala","♙","Ver equipe"],["message","↗","Enviar mensagem"],["csv","⇩","Baixar planilha da escala"],["links","⌁","Arquivos (cifras e VS)"]]],
  ...(isLeader()?[["Organizar",[["new-scale","＋","Cadastrar nova escala"],["editor","✎","Alterar escala"],["editor-music","♫","Adicionar músicas"],["new-member","＋","Adicionar novo membro"]]]]:[])
]; const account=isLeader()?`<div class="cloud-account"><i></i><span><b>Modo líder</b><small>${esc(state.storageSession?.user?.email||"")}</small></span></div><button class="btn btn-light btn-wide" data-action="reload-cloud">↻ Atualizar do banco</button><button class="btn btn-danger btn-wide" data-action="logout">Sair do modo líder</button>`:`<div class="visitor-account"><strong>Visualização pública</strong><small>Somente líderes podem alterar as escalas.</small></div><button class="btn btn-primary btn-wide" data-action="leader-login">Entrar como líder</button>`; return `<div class="drawer-overlay ${state.drawer?'open':''}" data-action="close-drawer"><aside class="drawer" onclick="event.stopPropagation()"><div class="drawer-head"><button class="icon-btn close" data-action="close-drawer">×</button><div class="drawer-logo">PIB</div><strong>Escala Louvor</strong><span>Servir com alegria, organizar com cuidado.</span></div>${groups.map(([t,items])=>`<div class="menu-group"><div class="menu-group-title">${t}</div>${items.map(([a,i,l])=>`<button class="menu-item" data-menu="${a}"><span class="mi">${i}</span>${l}</button>`).join("")}</div>`).join("")}<div class="menu-footer">${supabase?account:`<button class="btn btn-light btn-wide" data-action="reset">↻ Atualizar dados</button>`}</div></aside></div>`; }

async function appLogin(event){
  event.preventDefault();if(!supabase)return;
  const form=event.currentTarget,status=$('[data-app-auth-status]',form),button=$('button',form),email=form.elements.email.value.trim(),password=form.elements.password.value;
  button.disabled=true;button.textContent="Entrando…";status.textContent="";
  try{const {data,error}=await supabase.auth.signInWithPassword({email,password});if(error)throw error;state.storageSession=data.session;if(!await loadCloudData())throw new Error(state.cloudError);state.leaderLogin=false;state.selected=nearestScale()?.id;const scale=activeScale();if(scale)state.calendarDate=parseDate(scale.data);render();toast("Modo líder ativado")}
  catch(error){if(state.storageSession){state.cloudError=error?.message||"Não foi possível carregar o banco de dados.";render()}else{status.textContent=error?.message||"Não foi possível entrar.";button.disabled=false;button.textContent="Entrar"}}
}
async function appLogout(){if(!supabase)return;try{await supabase.auth.signOut()}finally{state.storageSession=null;state.cloudReady=false;state.cloudError="";state.leaderLogin=false;state.modal=null;state.drawer=false;state.editingScale=null;state.screen="escala";await loadCloudData();render()}}
function bindAuth(){
  $('[data-app-login]')?.addEventListener('submit',appLogin);
  $('[data-action="close-leader-login"]')?.addEventListener('click',()=>{state.leaderLogin=false;render()});
  $('[data-action="retry-cloud"]')?.addEventListener('click',async()=>{if(await loadCloudData()){state.selected=nearestScale()?.id;render()}else render()});
  $('[data-action="logout"]')?.addEventListener('click',appLogout);
}

function render(){ if(state.canvasRaf) cancelAnimationFrame(state.canvasRaf);if(state.leaderLogin){$("#app").innerHTML=authScreen();bindAuth();return}let content=state.screen==="escala"?scaleScreen():state.screen==="agenda"?agendaScreen():state.screen==="repertorio"?repertoireScreen():state.screen==="equipe"?teamScreen():editorScreen(); $("#app").innerHTML=shell(content); bind(); const canvas=$("[data-map-canvas]"); if(canvas) startRpgCanvas(canvas,state.editingScale||activeScale()); }
function navigate(screen){ if(state.screen==="editor"&&state.editingScale&&screen!=="editor"&&!confirm("Sair sem salvar as alterações da escala?"))return; if(screen!=="editor")state.editingScale=null;state.screen=screen; state.drawer=false; state.query=""; render(); window.scrollTo({top:0,behavior:"smooth"}); }

function scaleScreen(){ const s=activeScale(); if(!s) return empty("Nenhuma escala cadastrada"); return `<section class="screen">
  <div class="date-controls"><select class="date-select" data-action="select-scale" aria-label="Selecionar escala">${state.db.escalas.map(e=>`<option value="${e.id}" ${e.id===s.id?'selected':''}>${fmt(e.data,{weekday:"short",day:"2-digit",month:"short"})} · ${esc(e.culto.replace(/ \(.+/,""))}</option>`).join("")}</select><button class="btn btn-outline" data-action="calendar">▣ <span class="desktop-label">Calendário</span></button></div>
  ${state.calendar?calendar():""}<article class="culto-ribbon"><div><span>${fmt(s.data,{weekday:"long",day:"2-digit",month:"long"})}</span><h1>${esc(s.culto.replace(/ \(.+/,""))}</h1></div><div class="live-chip"><i></i>${s.equipe.length} na equipe</div></article>
  ${mapView(s,isLeader())}<div class="action-strip map-actions"><button class="btn btn-primary" data-action="message">↗ Enviar mensagem</button><button class="btn btn-gold" data-action="copy">▣ Copiar</button><button class="btn btn-light" data-action="csv">⇩ Baixar planilha</button><button class="btn btn-light" data-action="links">⌁ Arquivos</button>${isLeader()?'<button class="btn btn-outline" data-menu="editor">✎ Alterar escala</button>':''}</div>
  ${repertoireCard(s)}<div class="message-preview">${esc(buildMessage(s))}</div></section>`; }

function calendar(){ const d=new Date(state.calendarDate.getFullYear(),state.calendarDate.getMonth(),1); const first=d.getDay(), days=new Date(d.getFullYear(),d.getMonth()+1,0).getDate(); const cells=[]; for(let i=0;i<first;i++) cells.push("<span></span>"); for(let day=1;day<=days;day++){ const ds=iso(new Date(d.getFullYear(),d.getMonth(),day)); const scales=state.db.escalas.filter(e=>e.data===ds); const selected=activeScale()?.data===ds; cells.push(`<button class="cal-day ${scales.length?'has-scale':''} ${selected?'selected':''} ${ds===iso(new Date())?'today':''}" data-day="${ds}">${day}${scales.length?`<span class="cal-dots">${scales.map(()=>"<i></i>").join("")}</span>`:""}</button>`); } return `<div class="calendar card"><div class="calendar-head"><button class="icon-btn" data-cal="prev">‹</button><strong>${d.toLocaleDateString("pt-BR",{month:"long",year:"numeric"})}</strong><button class="icon-btn" data-cal="next">›</button></div><div class="calendar-grid">${["D","S","T","Q","Q","S","S"].map(x=>`<span class="cal-week">${x}</span>`).join("")}${cells.join("")}</div></div>`; }

function mapSlots(s){
  const fixed=Object.entries(POSITIONS).map(([funcao,posicao])=>({funcao,posicao}));
  const vocalSlots=(funcao,xs)=>{ const people=s.equipe.filter(e=>e.funcao===funcao); const total=Math.max(VOCAL_LIMITS[funcao],people.length); const positions=total===xs.length?xs:Array.from({length:total},(_,i)=>[funcao==="Vocal masculino"?20+i*10:62+i*9,31]); return positions.map((posicao,i)=>({funcao,posicao,slot:i,personId:people[i]?.id})); };
  return [...fixed,...vocalSlots("Vocal masculino",[[25,31],[35,31]]),...vocalSlots("Vocal feminino",[[65,31],[75,31],[85,31]])];
}
function mapView(s, editable=isLeader()){ const slots=mapSlots(s),hint=editable?"Toque em uma posição para organizar a equipe":"Visualização da equipe escalada"; return `<article class="map-card card"><div class="map-toolbar"><div><strong>MAPA DE OPERAÇÕES</strong><br><span>${hint}</span></div><span class="map-status"><i></i> cenário animado</span></div><div class="map-scroll"><div class="temple-map"><canvas class="rpg-canvas" data-map-canvas aria-label="Mapa animado da equipe"></canvas>${editable?slots.map(slot=>{const f=slot.funcao,[x,y]=slot.posicao;return `<button class="canvas-hotspot" style="left:${x}%;top:${y}%" data-position="${esc(f)}" aria-label="Editar ${esc(f)}"></button>`}).join(""):''}</div></div><div class="map-legend">${Object.keys(TEAM_LABEL).map(t=>`<span class="legend-item" style="--team:${TEAM_COLOR[t]}"><i class="legend-dot"></i>${TEAM_LABEL[t]}</span>`).join("")}</div><div class="map-sign"><span>✦</span> MAPA DE OPERAÇÕES DA IGREJA <span>✦</span></div></article>`; }

const CANVAS_COLORS={instrumentos:"#b77916",vocais:"#6b4fa0",lideranca:"#9a422b",transmissao:"#1d608a",audio:"#1a7b56",midia:"#648a10"};
function canvasRoleColor(f){ return f==="Vocal feminino"?"#bd3f7c":f==="Vocal masculino"?"#405daf":CANVAS_COLORS[TEAM[f]||"instrumentos"]; }
function hashCode(v){ return [...String(v)].reduce((a,c)=>(a*31+c.charCodeAt(0))>>>0,7); }
function avatarSettings(p={}){const h=hashCode(p.id||p.nome||"novo"),saved=p.avatar&&typeof p.avatar==="object"?p.avatar:{},inferred=(p.funcoes||[]).includes("Vocal feminino")?"feminino":(p.funcoes||[]).includes("Vocal masculino")?"masculino":"neutro";return{tipo:saved.tipo||inferred,pele:saved.pele||DEFAULT_AVATAR.pele,cabelo:saved.cabelo||DEFAULT_AVATAR.cabelo,estilo:saved.estilo||((h>>5)%3===0?"cacheado":inferred==="feminino"?"longo":"curto")}}
function roundRect(ctx,x,y,w,h,r,fill,stroke,line=2){ ctx.beginPath();ctx.roundRect(x,y,w,h,r);if(fill){ctx.fillStyle=fill;ctx.fill()}if(stroke){ctx.lineWidth=line;ctx.strokeStyle=stroke;ctx.stroke()} }
function drawPlant(ctx,x,y,s=1){ctx.fillStyle="#443225";ctx.fillRect(x-7*s,y+8*s,14*s,11*s);[[0,-17,-.1],[9,-11,.55],[-9,-10,-.55],[5,-22,.28],[-5,-22,-.28]].forEach(([dx,dy,r])=>{ctx.save();ctx.translate(x+dx*s,y+dy*s);ctx.rotate(r);ctx.fillStyle=dy<-18?"#4d913d":"#327332";ctx.fillRect(-4*s,0,8*s,20*s);ctx.restore()})}
function drawLamp(ctx,x,y,t){const glow=.65+Math.sin(t/260+x)*.12;ctx.save();ctx.globalAlpha=glow*.22;ctx.fillStyle="#ffd261";ctx.beginPath();ctx.arc(x,y,35,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;ctx.fillStyle="#34251b";ctx.fillRect(x-3,y-8,6,15);ctx.fillStyle="#ffe28c";ctx.fillRect(x-4,y-5,8,8);ctx.restore()}
function drawPew(ctx,x,y,w){ctx.fillStyle="#352317";ctx.fillRect(x-4,y+6,w+8,12);ctx.fillRect(x,y-7,w,8);ctx.fillStyle="#86522d";ctx.fillRect(x+3,y-5,w-6,5);ctx.fillRect(x,y+3,w,8);ctx.fillStyle="#b16c34";ctx.fillRect(x+4,y+4,w-8,3);ctx.fillStyle="#2a1d16";ctx.fillRect(x+3,y+17,7,8);ctx.fillRect(x+w-10,y+17,7,8)}
function drawDesk(ctx,x,y,w,screenColor,count=2){ctx.fillStyle="#2e2119";ctx.fillRect(x-5,y+7,w+10,29);ctx.fillStyle="#82502c";ctx.fillRect(x,y,w,24);ctx.fillStyle="#a66a35";ctx.fillRect(x+3,y+3,w-6,5);for(let i=0;i<count;i++){const sx=x+8+i*(w-20)/Math.max(1,count-1);ctx.fillStyle="#17262b";ctx.fillRect(sx,y-17,18,16);ctx.fillStyle=screenColor;ctx.fillRect(sx+3,y-14,12,9);ctx.fillStyle="#8ceaff";ctx.fillRect(sx+5,y-12,5,2)}ctx.fillStyle="#39251a";ctx.fillRect(x+8,y+29,8,18);ctx.fillRect(x+w-16,y+29,8,18)}
function drawScene(ctx,t){
  ctx.fillStyle="#0a3928";ctx.fillRect(0,0,800,1000);
  for(let i=0;i<210;i++){const x=(i*73)%800,y=(i*41)%1000,r=5+(i%5)*2;ctx.fillStyle=["#174c2e","#245c34","#2e6d3a","#0d4228"][i%4];ctx.fillRect(x-r,y-r,r*2,r*2)}
  ctx.fillStyle="#6c6656";ctx.fillRect(31,30,738,930);ctx.fillStyle="#a69a80";ctx.fillRect(42,41,716,908);ctx.fillStyle="#3c392f";for(let y=42;y<950;y+=21)for(let x=42+(y/21%2)*18;x<758;x+=37){ctx.fillRect(x,y,2,19);ctx.fillRect(42,y,716,2)}
  ctx.fillStyle="#8d5528";ctx.fillRect(48,48,704,308);ctx.fillStyle="#ae6a30";for(let y=50;y<350;y+=16){ctx.fillRect(50,y,700,13);ctx.fillStyle="#75411f";ctx.fillRect(50,y+13,700,3);ctx.fillStyle="#ae6a30"}
  ctx.fillStyle="#81745f";ctx.fillRect(48,48,704,76);ctx.fillStyle="#4f493e";for(let x=48;x<752;x+=34)ctx.fillRect(x,48,2,76);for(let y=48;y<124;y+=18)ctx.fillRect(48,y,704,2);
  ctx.fillStyle="#3b281a";ctx.fillRect(236,48,94,76);ctx.fillRect(470,48,94,76);ctx.fillStyle="#65401f";for(let x of [242,258,274,290,306,476,492,508,524,540])ctx.fillRect(x,50,9,72);
  [110,250,400,550,690].forEach(x=>drawLamp(ctx,x,105,t));drawPlant(ctx,82,135,.85);drawPlant(ctx,382,135,.85);drawPlant(ctx,610,135,.85);drawPlant(ctx,718,135,.85);
  ctx.fillStyle="#cab99d";ctx.fillRect(48,356,704,374);ctx.fillStyle="#a99a82";for(let x=48;x<752;x+=32)ctx.fillRect(x,356,1,374);for(let y=356;y<730;y+=32)ctx.fillRect(48,y,704,1);
  ctx.save();ctx.globalAlpha=.16;let g=ctx.createLinearGradient(65,400,300,650);g.addColorStop(0,"#8ad9ff");g.addColorStop(1,"transparent");ctx.fillStyle=g;ctx.beginPath();ctx.moveTo(80,445);ctx.lineTo(300,690);ctx.lineTo(125,690);ctx.closePath();ctx.fill();ctx.scale(-1,1);ctx.translate(-800,0);ctx.fill();ctx.restore();
  [475,570,665].forEach(y=>{drawPew(ctx,150,y,190);drawPew(ctx,460,y,190)});drawPlant(ctx,82,687,.8);drawPlant(ctx,718,687,.8);
  ctx.fillStyle="#e1d7c4";ctx.fillRect(42,720,716,27);ctx.fillStyle="#425158";for(let x=52;x<752;x+=24)ctx.fillRect(x,724,4,20);ctx.fillStyle="#7c6e58";ctx.fillRect(42,744,716,5);
  ctx.fillStyle="#315d70";ctx.fillRect(48,749,704,203);ctx.fillStyle="#264c5e";for(let x=48;x<752;x+=28)ctx.fillRect(x,749,1,203);for(let y=749;y<952;y+=28)ctx.fillRect(48,y,704,1);
  drawDesk(ctx,92,777,170,"#d5a23a",3);drawDesk(ctx,316,777,170,"#36a9ca",3);drawDesk(ctx,540,777,150,"#4ebc7f",2);
  ctx.fillStyle="#81512d";for(let i=0;i<8;i++){ctx.fillRect(700+i*4,785+i*20,52-i*4,8)}
  ctx.save();ctx.translate(16,245);ctx.rotate(-Math.PI/2);roundRect(ctx,-62,-13,124,27,4,"#073449","#c99a30",3);ctx.fillStyle="#f4da82";ctx.font="14px Silkscreen";ctx.textAlign="center";ctx.fillText("PALCO",0,5);ctx.restore();ctx.save();ctx.translate(16,850);ctx.rotate(-Math.PI/2);roundRect(ctx,-72,-13,144,27,4,"#073449","#c99a30",3);ctx.fillStyle="#f4da82";ctx.font="12px Silkscreen";ctx.textAlign="center";ctx.fillText("MEZANINO",0,5);ctx.restore();
}
function drawAccessory(ctx,f,x,y,phase){ctx.save();ctx.lineWidth=3;ctx.strokeStyle="#172328";if(f.includes("Vocal")||f==="Dirigente"){ctx.beginPath();ctx.moveTo(x+17,y-19);ctx.lineTo(x+17,y+5);ctx.stroke();ctx.fillStyle="#718086";ctx.fillRect(x+14,y-23,7,7)}else if(["Guitarra","Violão","Baixo"].includes(f)){ctx.translate(x+3,y-14);ctx.rotate(-.28);ctx.fillStyle=f==="Baixo"?"#a84632":"#d58b35";ctx.beginPath();ctx.ellipse(0,0,11,8,0,0,Math.PI*2);ctx.fill();ctx.fillStyle="#55351e";ctx.fillRect(7,-2,18,4);ctx.strokeStyle="#f4d788";ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(-6,0);ctx.lineTo(24,0);ctx.stroke()}else if(["Teclado","Piano","Órgão"].includes(f)){ctx.fillStyle="#17272b";ctx.fillRect(x-18,y-8,37,11);ctx.fillStyle="#eee7d5";for(let i=0;i<7;i++)ctx.fillRect(x-15+i*5,y-6,3,6)}else if(f==="Bateria"){ctx.fillStyle="#b55d31";ctx.beginPath();ctx.arc(x,y-5,13,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.beginPath();ctx.moveTo(x-18,y-22);ctx.lineTo(x-6,y-10);ctx.moveTo(x+18,y-22);ctx.lineTo(x+6,y-10);ctx.stroke()}else if(f.includes("Câmera")){ctx.fillStyle="#263d44";ctx.fillRect(x-2,y-25,20,14);ctx.fillStyle="#75abc0";ctx.fillRect(x+1,y-22,8,7);ctx.beginPath();ctx.moveTo(x+8,y-11);ctx.lineTo(x,y+8);ctx.moveTo(x+8,y-11);ctx.lineTo(x+18,y+8);ctx.stroke()}else if(["Som","Mídia","Mesa de corte"].includes(f)){ctx.beginPath();ctx.arc(x,y-32,12,Math.PI,0);ctx.stroke();ctx.fillStyle="#182b31";ctx.fillRect(x-14,y-33,4,11);ctx.fillRect(x+10,y-33,4,11)}ctx.restore()}
function drawCharacter(ctx,x,y,p,f,t,i){const h=hashCode(p.id),av=avatarSettings(p),skin=av.pele,hair=av.cabelo,female=av.tipo==="feminino",male=av.tipo==="masculino",backFacing=["Som","Mesa de corte","Mídia"].includes(f),phase=t/360+i*.8,bob=Math.round(Math.sin(phase)*2),step=Math.sin(phase)>0?2:-2,baseY=Math.round(y+bob),color=canvasRoleColor(f);x=Math.round(x+Math.sin(t/1250+i)*2);
  ctx.save();ctx.imageSmoothingEnabled=false;ctx.globalAlpha=.36;ctx.fillStyle="#071718";ctx.beginPath();ctx.ellipse(x,baseY+4,17-Math.abs(bob),5,0,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;if(backFacing){ctx.fillStyle="#26383d";ctx.fillRect(x-15,baseY-29,30,28);ctx.fillStyle="#17262a";ctx.fillRect(x-18,baseY-24,5,25);ctx.fillRect(x+13,baseY-24,5,25)}
  ctx.fillStyle="#172d42";ctx.fillRect(x-9,baseY-10,7,13+step);ctx.fillRect(x+3,baseY-10,7,13-step);ctx.fillStyle="#171d21";ctx.fillRect(x-10,baseY+1+step,9,4);ctx.fillRect(x+2,baseY+1-step,9,4);
  if(female){ctx.fillStyle=color;ctx.beginPath();ctx.moveTo(x-11,baseY-29);ctx.lineTo(x+11,baseY-29);ctx.lineTo(x+15,baseY-8);ctx.lineTo(x-15,baseY-8);ctx.fill()}else{ctx.fillStyle=color;ctx.fillRect(x-12,baseY-31,24,22);ctx.fillStyle="#f2d07b";ctx.fillRect(x-2,baseY-30,4,20);if(male){ctx.fillStyle="#263f7d";ctx.fillRect(x-12,baseY-29,5,18);ctx.fillRect(x+7,baseY-29,5,18)}}
  const arm=Math.round(Math.sin(phase)*3);ctx.fillStyle=skin;ctx.fillRect(x-16,baseY-28+arm,5,17);ctx.fillRect(x+12,baseY-28-arm,5,17);
  ctx.fillStyle=hair;if(av.estilo==="longo"){ctx.fillRect(x-12,baseY-51,24,25);ctx.fillRect(x-15,baseY-45,5,20);ctx.fillRect(x+11,baseY-45,5,20)}else if(av.estilo==="cacheado"){[[-11,-49],[-5,-53],[2,-53],[9,-49],[-13,-43],[11,-43]].forEach(([dx,dy])=>ctx.fillRect(x+dx,baseY+dy,7,7))}else if(av.estilo==="raspado"){ctx.fillRect(x-9,baseY-49,18,3)}else{ctx.fillRect(x-10,baseY-51,20,10);if((h>>5)%2)ctx.fillRect(x-13,baseY-48,5,8)}ctx.fillStyle=backFacing?hair:skin;ctx.fillRect(x-9,baseY-46,18,16);ctx.fillStyle=hair;if(av.estilo!=="raspado")ctx.fillRect(x-9,baseY-49,18,5);else ctx.fillRect(x-9,baseY-48,18,2);if(male&&av.estilo!=="longo")ctx.fillRect(x-10,baseY-47,4,8);if(!backFacing){ctx.fillStyle="#172126";ctx.fillRect(x-5,baseY-40,3,3);ctx.fillRect(x+3,baseY-40,3,3);ctx.fillStyle="#b95d4b";ctx.fillRect(x-2,baseY-35,5,2)}else{ctx.fillStyle=skin;ctx.fillRect(x-11,baseY-42,3,7);ctx.fillRect(x+9,baseY-42,3,7)}
  drawAccessory(ctx,f,x,baseY,phase);if(female||male){ctx.fillStyle=color;ctx.beginPath();ctx.arc(x+17,baseY-48,8,0,Math.PI*2);ctx.fill();ctx.strokeStyle="#fff";ctx.lineWidth=2;ctx.stroke();ctx.fillStyle="#fff";ctx.font="9px Silkscreen";ctx.textAlign="center";ctx.fillText(female?"F":"M",x+17,baseY-45)}ctx.restore();
}
function refreshAvatarPreview(){const canvas=$("[data-avatar-preview]");if(!canvas)return;const form=canvas.closest("form"),ctx=canvas.getContext("2d"),p={id:form.elements.id.value||"preview",avatar:{tipo:form.elements.avatarTipo.value,estilo:form.elements.avatarEstilo.value,pele:form.elements.avatarPele.value,cabelo:form.elements.avatarCabelo.value}};ctx.clearRect(0,0,120,105);ctx.imageSmoothingEnabled=false;ctx.fillStyle="#123d38";ctx.fillRect(0,0,120,105);ctx.fillStyle="#a66a35";for(let y=0;y<105;y+=12){ctx.fillRect(0,y,120,9);ctx.fillStyle="#75411f";ctx.fillRect(0,y+9,120,3);ctx.fillStyle="#a66a35"}drawCharacter(ctx,60,82,p,"Dirigente",0,0)}
function drawPositionLabel(ctx,x,y,f,name,slot,empty,t){const vocal=f.startsWith("Vocal"),label=vocal?`${f==="Vocal masculino"?"VOCAL MASC.":"VOCAL FEM."} ${slot+1}`:f.toUpperCase(),color=canvasRoleColor(f),w=Math.max(70,Math.min(126,label.length*6+16)),pulse=.55+Math.sin(t/400+x)*.2;ctx.save();if(empty){ctx.setLineDash([5,4]);ctx.lineWidth=2;ctx.strokeStyle=color;ctx.globalAlpha=pulse;ctx.beginPath();ctx.arc(x,y-24,19,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);ctx.globalAlpha=1;ctx.fillStyle="#fff0b5";ctx.font="12px Silkscreen";ctx.textAlign="center";ctx.fillText(vocal?(f.endsWith("masculino")?"M":"F"):"+",x,y-20)}roundRect(ctx,x-w/2,y+9,w,29,5,"#082d33",color,2);ctx.fillStyle="#fff";ctx.font="7px Silkscreen";ctx.textAlign="center";ctx.fillText(label,x,y+20);ctx.fillStyle="#ffeaa5";ctx.font="bold 9px DM Sans";ctx.fillText(name||"vaga disponível",x,y+32);ctx.restore()}
function startRpgCanvas(canvas,s){const W=800,H=1000,dpr=Math.min(devicePixelRatio||1,2),ctx=canvas.getContext("2d");canvas.width=W*dpr;canvas.height=H*dpr;const slots=mapSlots(s);const reduce=matchMedia("(prefers-reduced-motion: reduce)").matches;let last=-34;function frame(t=0){if(t-last>=33){last=t;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.imageSmoothingEnabled=false;drawScene(ctx,t);slots.forEach((slot,i)=>{const f=slot.funcao,x=slot.posicao[0]*8,y=slot.posicao[1]*10,isVocalSlot=slot.slot!==undefined,people=isVocalSlot?(slot.personId?[member(slot.personId)].filter(Boolean):[]):s.equipe.filter(e=>e.funcao===f).map(e=>member(e.id)).filter(Boolean);if(people.length){people.forEach((p,j)=>drawCharacter(ctx,x+(j-(people.length-1)/2)*28,y,p,f,t,i+j));drawPositionLabel(ctx,x,y,f,people.map(p=>shortName(p.nome)).join(", "),slot.slot||0,false,t)}else drawPositionLabel(ctx,x,y,f,"",slot.slot||0,true,t)})}if(!reduce&&canvas.isConnected)state.canvasRaf=requestAnimationFrame(frame)}frame()}
function resourceButtons(m){const resources=[{key:"youtube",label:"Referência",icon:"▶",kind:"reference"},{key:"cifra",label:"Abrir cifra",icon:"▤",kind:"pdf"},{key:"vs",label:"Ouvir VS",icon:"♪",kind:"mp3"}];return `<div class="resource-row">${resources.map(r=>{const url=safeUrl(m[r.key]);if(!url)return `<span class="resource-link unavailable" aria-disabled="true"><i>${r.icon}</i>${r.label}</span>`;if(r.kind==="reference"||r.kind==="pdf")return `<a class="resource-link ${r.kind}" href="${esc(url)}" target="_blank" rel="noopener noreferrer" onclick="event.stopPropagation()"><i>${r.icon}</i>${r.label}<b>↗</b></a>`;return `<button type="button" class="resource-link mp3" data-play-url="${esc(url)}" data-play-title="${esc(m.titulo)}"><i>${r.icon}</i>${r.label}<b>▶</b></button>`}).join("")}</div>`}
function fileName(title,kind){return `${String(title||"arquivo").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/gi,"-").replace(/^-|-$/g,"").toLowerCase()}.${kind}`}
function repertoireCard(s){ return `<article class="card pad"><div class="section-head"><h2>Repertório</h2><span class="muted">${s.repertorio.length} itens</span></div><div class="song-list">${s.repertorio.length?s.repertorio.map(r=>{const m=music(r.musicaId)||{}; return `<div class="song-row"><span class="moment-badge">${esc(r.momento)}</span><div class="song-title"><strong>${esc(m.tipo==="Hino"?`${m.hinario} ${m.numero} · ${m.titulo}`:m.titulo)}</strong>${resourceButtons(m)}</div><span class="key-badge">${esc(r.tom||"—")}</span></div>`;}).join(""):empty("Nenhuma música adicionada")}</div></article>`; }

function agendaScreen(){ const now=iso(new Date()); const upcoming=[...state.db.escalas].filter(e=>e.data>=now).sort((a,b)=>a.data.localeCompare(b.data)), past=[...state.db.escalas].filter(e=>e.data<now).sort((a,b)=>b.data.localeCompare(a.data)); const cards=x=>x.map(agendaCard).join(""); return `<section class="screen"><div class="page-heading"><div><span class="eyebrow">Planejamento</span><h1>Agenda</h1><span class="muted">${state.db.escalas.length} cultos cadastrados</span></div>${isLeader()?'<button class="btn btn-gold" data-action="new-scale">＋ Nova</button>':''}</div><div class="divider-title">Próximas escalas</div><div class="agenda-list">${upcoming.length?cards(upcoming):empty("Nenhuma próxima escala")}</div><div class="divider-title">Escalas anteriores</div><div class="agenda-list">${past.length?cards(past):empty("Nenhuma escala anterior")}</div></section>`; }
function agendaCard(s){ const d=parseDate(s.data), leader=s.equipe.find(x=>x.funcao==="Dirigente"); const counts={}; s.equipe.forEach(e=>counts[TEAM[e.funcao]||"instrumentos"]=(counts[TEAM[e.funcao]||"instrumentos"]||0)+1); return `<article class="agenda-card card"><div class="agenda-top"><div class="date-tile"><strong>${d.getDate()}</strong><span>${d.toLocaleDateString("pt-BR",{month:"short"})}</span></div><div class="agenda-info"><h3>${esc(s.culto.replace(/ \(.+/,""))}</h3><p>${fmt(s.data,{weekday:"long"})} · Dirigente: ${esc(member(leader?.id)?.nome||"A definir")}</p><div class="tags">${Object.entries(counts).map(([t,n])=>`<span class="tag" style="--team:${TEAM_COLOR[t]}">${TEAM_LABEL[t]} ${n}</span>`).join("")}<span class="tag">♫ ${s.repertorio.length}</span></div></div></div><div class="agenda-actions"><button class="btn btn-small btn-light" data-copy-id="${s.id}">Copiar mensagem</button><button class="btn btn-small btn-primary" data-open-id="${s.id}">Abrir</button>${isLeader()?`<button class="btn btn-small btn-outline" data-duplicate="${s.id}">Duplicar</button><button class="btn btn-small btn-danger" data-delete-scale="${s.id}">Excluir</button>`:''}</div></article>`; }

function repertoireScreen(){ const q=state.query.toLocaleLowerCase("pt-BR"); const items=state.db.musicas.filter(m=>`${m.titulo} ${m.hinario} ${m.numero}`.toLocaleLowerCase("pt-BR").includes(q)).sort((a,b)=>a.titulo.localeCompare(b.titulo,"pt-BR")); return `<section class="screen"><div class="page-heading"><div><span class="eyebrow">Banco de músicas</span><h1>Repertório</h1><span class="muted">${state.db.musicas.length} músicas e hinos</span></div>${isLeader()?'<button class="btn btn-gold" data-action="new-song">＋ Adicionar</button>':''}</div><div class="search-bar"><input type="search" value="${esc(state.query)}" data-search placeholder="Buscar título, hinário ou número"></div><div class="directory-list">${items.map(m=>{const o=occurrences("s",m.id); return `<article class="song-card card" ${isLeader()?`data-edit-song="${m.id}"`:''}><span class="song-symbol">${m.tipo==="Hino"?'♬':'♫'}</span><div class="song-card-content"><h3>${esc(m.tipo==="Hino"?`${m.hinario} ${m.numero} · ${m.titulo}`:m.titulo)}</h3><p>${o.count} vez${o.count===1?'':'es'} · ${o.last?`última em ${fmt(o.last,{day:"2-digit",month:"2-digit",year:"numeric"})}`:"ainda não cantada"}</p>${resourceButtons(m)}</div><span class="key-badge">${esc(m.tom||"—")}</span></article>`;}).join("")}</div></section>`; }

function teamScreen(){ const q=state.query.toLocaleLowerCase("pt-BR"); const items=state.db.membros.filter(m=>`${m.nome} ${m.funcoes.join(' ')}`.toLocaleLowerCase("pt-BR").includes(q)).sort((a,b)=>a.nome.localeCompare(b.nome,"pt-BR")); return `<section class="screen"><div class="page-heading"><div><span class="eyebrow">Pessoas e talentos</span><h1>Equipe</h1><span class="muted">${state.db.membros.length} membros cadastrados</span></div>${isLeader()?'<button class="btn btn-gold" data-action="new-member">＋ Adicionar</button>':''}</div><div class="search-bar"><input type="search" value="${esc(state.query)}" data-search placeholder="Buscar nome ou função"></div><div class="directory-list">${items.map(m=>{const o=occurrences("m",m.id); return `<article class="directory-card card" ${isLeader()?`data-edit-member="${m.id}"`:''}><span class="member-avatar">${esc(m.nome.split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase())}</span><div class="member-info"><h3>${esc(m.nome)}</h3><p>${esc(m.whatsapp||"WhatsApp não informado")}</p><div class="tags">${m.funcoes.map(f=>`<span class="tag" style="--team:${teamColor(f)}">${esc(f)}</span>`).join("")}</div></div><div class="stats"><strong>${o.count}</strong>escalas<br>${o.last?fmt(o.last,{day:"2-digit",month:"2-digit"}):"—"}</div></article>`;}).join("")}</div><p class="cloud-footnote"><i></i>${supabase?'Visualização pública sincronizada com o Supabase.':'Dados armazenados neste dispositivo.'}</p></section>`; }

function editorScreen(){ const s=state.editingScale || activeScale(); if(!s) return empty("Crie uma escala para começar"); return `<section class="screen"><div class="page-heading editor-heading"><div><span class="eyebrow">Organizar culto</span><h1>${state.editingScale?.__new?'Nova escala':'Editar escala'}</h1><span class="muted">Revise a equipe e o repertório antes de publicar.</span></div><div class="editor-actions"><button class="btn btn-light" data-action="cancel-scale">Cancelar</button><button class="btn btn-primary" data-action="save-scale">✓ Salvar escala</button></div></div><div class="form-card card"><div class="form-grid"><div class="field"><label>Data</label><input type="date" data-scale-field="data" value="${s.data}"></div><div class="field"><label>Culto</label><select data-scale-field="culto">${CULTOS.map(c=>`<option ${c===s.culto?'selected':''}>${esc(c)}</option>`).join("")}</select></div></div></div><article class="editor-section card pad"><div class="section-head"><h2>Equipe</h2><div class="segmented"><button class="${state.editorMode==='mapa'?'active':''}" data-editor-mode="mapa">Mapa</button><button class="${state.editorMode==='lista'?'active':''}" data-editor-mode="lista">Lista</button></div></div>${state.editorMode==='mapa'?mapView(s):teamEditorList(s)}</article>${repertoireEditor(s)}<article class="editor-section card pad"><div class="form-grid"><div class="field span-2"><label>Saudação</label><input data-scale-field="saudacao" value="${esc(s.saudacao)}"></div><div class="field"><label>Aviso de ensaio</label><textarea data-scale-field="ensaio">${esc(s.ensaio)}</textarea></div><div class="field"><label>Observações</label><textarea data-scale-field="obs">${esc(s.obs)}</textarea></div></div></article><article class="editor-section card pad"><div class="section-head"><h2>Prévia da mensagem</h2><button class="btn btn-small btn-gold" data-action="copy-editor">Copiar</button></div><div class="message-preview">${esc(buildMessage(s))}</div></article><div class="mobile-save-bar"><button class="btn btn-light" data-action="cancel-scale">Cancelar</button><button class="btn btn-primary" data-action="save-scale">✓ Salvar escala</button></div></section>`; }
function teamEditorList(s){ return `<div>${FUNCOES.map(f=>{const names=s.equipe.filter(e=>e.funcao===f).map(e=>member(e.id)?.nome).filter(Boolean), limit=VOCAL_LIMITS[f]; return `<button class="menu-item function-group" data-position="${esc(f)}"><span class="legend-dot" style="background:${teamColor(f)}"></span><span style="flex:1"><span class="function-line"><strong>${esc(f)}</strong><span class="count">${limit?`${names.length}/${limit} vagas`:`${names.length} escalado${names.length===1?'':'s'}`}</span></span><span class="muted" style="font-size:11px">${esc(names.join(', ')||'Toque para escolher')}</span></span><span>›</span></button>`;}).join("")}</div>`; }
function repertoireEditor(s){ return `<article class="editor-section card pad"><div class="section-head"><h2>Repertório</h2><button class="btn btn-small btn-gold" data-action="add-editor-song">＋ Música</button></div>${s.repertorio.length?s.repertorio.map((r,i)=>{const m=music(r.musicaId)||{};return `<div class="editor-song"><div class="editor-song-info"><strong>${esc(m.tipo==='Hino'?`${m.hinario} ${m.numero} · ${m.titulo}`:m.titulo)}</strong>${resourceButtons(m)}</div><input aria-label="Tom" value="${esc(r.tom)}" data-song-key="${r.chave}"><select data-song-moment="${r.chave}">${MOMENTOS.map(x=>`<option ${x===r.momento?'selected':''}>${x}</option>`).join("")}</select><div class="reorder"><button class="square-btn" data-move-song="${r.chave}" data-dir="-1">↑</button><button class="square-btn" data-move-song="${r.chave}" data-dir="1">↓</button><button class="square-btn" data-remove-song="${r.chave}">×</button></div></div>`;}).join(""):empty("Adicione músicas para este culto")}</article>`; }

function sheet(){ if(!state.sheet) return ""; const f=state.sheet, s=state.editingScale||activeScale(), limit=VOCAL_LIMITS[f],editing=Boolean(state.editingScale); const candidates=state.db.membros.filter(m=>m.funcoes.includes(f)); return `<div class="sheet-overlay open" data-action="close-sheet"><div class="sheet" role="dialog" aria-modal="true" aria-label="Selecionar ${esc(f)}" onclick="event.stopPropagation()"><div class="sheet-handle"></div><div class="section-head"><div><h2>${esc(f)}</h2><span class="muted">${limit?`${limit} vagas individuais · `:""}${editing?'As alterações serão aplicadas ao salvar a escala.':'As alterações são salvas neste dispositivo.'}</span></div><button class="icon-btn" data-action="close-sheet" aria-label="Fechar">×</button></div><div class="candidate-list">${candidates.length?candidates.map(m=>{const sel=s.equipe.some(e=>e.id===m.id&&e.funcao===f); const conflict=s.equipe.some(e=>e.id===m.id&&e.funcao!==f)&&!([f,...s.equipe.filter(e=>e.id===m.id).map(e=>e.funcao)].every(x=>x==='Dirigente'||x.startsWith('Vocal'))); return `<button class="candidate ${sel?'selected':''}" data-candidate="${m.id}" ${conflict?'disabled':''}><span class="member-avatar">${esc(m.nome[0])}</span><span><strong>${esc(m.nome)}</strong><br><small>${conflict?'Já escalado em outra função':esc(m.whatsapp||'Sem WhatsApp')}</small></span><span class="check">${sel?'✓':''}</span></button>`;}).join(""):empty("Nenhum membro possui esta função. Edite o cadastro da equipe.")}</div></div></div>`; }
function modal(){ if(!state.modal) return ""; if(state.modal.type==="song-picker"){ const scale=state.editingScale||activeScale(),selected=new Set(scale?.repertorio.map(r=>r.musicaId)||[]),list=[...state.db.musicas].sort((a,b)=>a.titulo.localeCompare(b.titulo,"pt-BR")); return `<div class="modal-overlay" data-action="close-modal"><div class="modal song-picker-modal" role="dialog" aria-modal="true" aria-label="Escolher música" onclick="event.stopPropagation()"><div class="section-head"><div><h2>Escolher música</h2><span class="muted">Consulte a referência, a letra ou o VS antes de adicionar.</span></div><button class="icon-btn" data-action="close-modal" aria-label="Fechar">×</button></div><div class="search-bar"><input data-picker-search autofocus placeholder="Buscar no banco de músicas"></div><div class="candidate-list song-picker-list" data-picker-list>${list.map(m=>{const added=selected.has(m.id);return `<article class="candidate song-candidate ${added?'selected':''}" data-song-candidate="${m.id}"><span class="song-symbol">♫</span><div class="song-candidate-info"><strong>${esc(m.titulo)}</strong><small>${esc(m.tipo==='Hino'?`${m.hinario} ${m.numero}`:`Tom padrão ${m.tom||'—'}`)}</small>${resourceButtons(m)}</div><button type="button" class="add-song-button" data-pick-song="${m.id}" ${added?'disabled':''} aria-label="${added?'Música já adicionada':`Adicionar ${esc(m.titulo)}`}">${added?'✓ <span>Adicionada</span>':'＋ <span>Adicionar</span>'}</button></article>`}).join("")}</div></div></div>`; } const type=state.modal.type, item=state.modal.item||{}; return `<div class="modal-overlay" data-action="close-modal"><form class="modal" role="dialog" aria-modal="true" data-form="${type}" onclick="event.stopPropagation()"><div class="section-head"><h2>${item.id?'Editar':'Novo'} ${type==='member'?'membro':'item do repertório'}</h2><button type="button" class="icon-btn" data-action="close-modal" aria-label="Fechar">×</button></div>${type==='member'?memberForm(item):songForm(item)}<div class="form-actions"><button type="button" class="btn btn-light" data-action="close-modal">Cancelar</button><button class="btn btn-primary">Salvar</button></div></form></div>`; }
function memberForm(m){const av=avatarSettings(m);return `<input type="hidden" name="id" value="${esc(m.id)}"><div class="form-grid"><div class="field span-2"><label>Nome</label><input name="nome" required value="${esc(m.nome)}"></div><div class="field span-2"><label>WhatsApp</label><input name="whatsapp" placeholder="(67) 99999-9999" value="${esc(m.whatsapp)}"></div><div class="avatar-editor span-2"><div class="avatar-preview-wrap"><canvas width="120" height="105" data-avatar-preview></canvas><strong>Prévia do avatar</strong></div><div class="avatar-controls"><div class="field"><label>Apresentação</label><select name="avatarTipo"><option value="neutro" ${av.tipo==='neutro'?'selected':''}>Neutra</option><option value="masculino" ${av.tipo==='masculino'?'selected':''}>Masculina</option><option value="feminino" ${av.tipo==='feminino'?'selected':''}>Feminina</option></select></div><div class="field"><label>Estilo do cabelo</label><select name="avatarEstilo"><option value="curto" ${av.estilo==='curto'?'selected':''}>Curto</option><option value="longo" ${av.estilo==='longo'?'selected':''}>Longo</option><option value="cacheado" ${av.estilo==='cacheado'?'selected':''}>Cacheado</option><option value="raspado" ${av.estilo==='raspado'?'selected':''}>Raspado</option></select></div><div class="field color-field"><label>Tom de pele</label><input type="color" name="avatarPele" value="${esc(av.pele)}"></div><div class="field color-field"><label>Cor do cabelo</label><input type="color" name="avatarCabelo" value="${esc(av.cabelo)}"></div></div></div><div class="field span-2"><label>Funções</label><div class="chips">${FUNCOES.map(f=>`<button type="button" class="chip ${(m.funcoes||[]).includes(f)?'selected':''}" style="--team:${teamColor(f)}" data-form-function="${esc(f)}">${esc(f)}</button>`).join("")}</div></div></div>`; }
function storagePanel(){if(!supabase)return `<div class="storage-panel storage-off span-2"><span class="storage-icon">☁</span><div><strong>Upload ainda não configurado</strong><p>Preencha as variáveis do Supabase no arquivo <code>.env.local</code>. Os links manuais continuam funcionando.</p></div></div>`;if(!state.storageSession)return `<div class="storage-panel span-2"><span class="storage-icon">☁</span><div class="storage-login"><strong>Entrar para enviar arquivos</strong><p>Use uma conta criada no Supabase Authentication.</p><div><input type="email" data-storage-email placeholder="E-mail"><input type="password" data-storage-password placeholder="Senha"><button type="button" class="btn btn-small btn-primary" data-storage-login>Entrar</button></div><small data-storage-auth-status></small></div></div>`;return `<div class="storage-panel span-2"><div class="storage-account"><span><b>☁ Supabase conectado</b><small>${esc(state.storageSession.user.email||"")}</small></span><button type="button" class="btn btn-small btn-light" data-storage-logout>Sair</button></div><div class="upload-grid"><label class="upload-box pdf-upload"><input type="file" accept="application/pdf,.pdf" data-storage-file="pdf"><span>▤</span><strong>Enviar cifra/letra</strong><small>PDF · até 15 MB</small><em data-upload-status="pdf">Escolher arquivo</em></label><label class="upload-box mp3-upload"><input type="file" accept="audio/mpeg,.mp3" data-storage-file="mp3"><span>♪</span><strong>Enviar VS</strong><small>MP3 · até 50 MB</small><em data-upload-status="mp3">Escolher arquivo</em></label></div></div>`}
function songForm(m){ return `<input type="hidden" name="id" value="${esc(m.id)}"><div class="form-grid"><div class="field"><label>Tipo</label><select name="tipo"><option ${m.tipo==='Música'?'selected':''}>Música</option><option ${m.tipo==='Hino'?'selected':''}>Hino</option></select></div><div class="field"><label>Tom padrão</label><input name="tom" value="${esc(m.tom)}"></div><div class="field"><label>Hinário</label><select name="hinario"><option></option><option ${m.hinario==='CC'?'selected':''}>CC</option><option ${m.hinario==='HCC'?'selected':''}>HCC</option></select></div><div class="field"><label>Número</label><input name="numero" value="${esc(m.numero)}"></div><div class="field span-2"><label>Título</label><input name="titulo" required value="${esc(m.titulo)}"></div><div class="field span-2"><label>Link de referência (YouTube)</label><input name="youtube" type="url" placeholder="https://youtube.com/…" value="${esc(m.youtube)}"></div>${storagePanel()}<div class="field"><label>PDF da cifra/letra <small>ou cole a URL</small></label><input name="cifra" type="url" placeholder="https://…/cifra.pdf" value="${esc(m.cifra)}"></div><div class="field"><label>VS em MP3 <small>ou cole a URL</small></label><input name="vs" type="url" placeholder="https://…/vs.mp3" value="${esc(m.vs)}"></div></div>`; }
function empty(text){ return `<div class="empty-state"><span class="empty-icon">♩</span>${esc(text)}</div>`; }

function buildMessage(s){ const by=f=>s.equipe.filter(e=>e.funcao===f).map(e=>member(e.id)?.nome).filter(Boolean); const vocalMale=by("Vocal masculino"),vocalFemale=by("Vocal feminino"); const instruments=["Violão","Guitarra","Baixo","Teclado","Bateria"].flatMap(f=>by(f).map(n=>`${n} (${f})`)), transmission=[["Mesa de corte",by("Mesa de corte")],["Câmera 1",by("Câmera 1")],["Câmera 2",by("Câmera 2")]].flatMap(([f,names])=>names.map(n=>`${n} (${f})`)); const rows=s.repertorio.map(r=>({r,m:music(r.musicaId)})).filter(x=>x.m); const openings=rows.filter(x=>x.r.momento==="Abertura").map(x=>songText(x,false)); const praise=rows.filter(x=>x.r.momento==="Louvor").map(x=>`- ${songText(x,true)}`); const special=m=>rows.filter(x=>x.r.momento===m).map(x=>songText(x,false)).join(", "); const day=fmt(s.data,{weekday:"long"}); const greetingText=(s.saudacao||"Olá!").trim(),greeting=/[.!?]$/.test(greetingText)?greetingText:`${greetingText}!`; const lines=[greeting,`*Segue a escala para o culto de ${day}, ${fmt(s.data,{day:"2-digit",month:"2-digit"})}*`,"",vocalMale.length?`Vocal masculino: ${vocalMale.join(', ')}`:"",vocalFemale.length?`Vocal feminino: ${vocalFemale.join(', ')}`:"",instruments.length?`Instrumental: ${instruments.join(', ')}`:"","",rows.length?"Músicas e Hinos:":"","",...openings,...praise,special("Oferta")?`Oferta: ${special("Oferta")}`:"",special("Batismo")?`Batismo: ${special("Batismo")}`:"",special("Ceia")?`Ceia: ${special("Ceia")}`:"",(by("Piano").length||by("Órgão").length)?`Piano e órgão: ${[...by('Piano'),...by('Órgão')].join(' e ')}`:"",(by("Som").length||by("Mídia").length)?`Som e mídia: ${[...by('Som'),...by('Mídia')].join(', ')}`:"",transmission.length?`Transmissão: ${transmission.join(', ')}`:"",s.ensaio?`✅ ${s.ensaio}`:"",s.obs?`Observação: ${s.obs}`:""]; return cleanLines(lines).join("\n"); }
function songText({r,m},link=true){ const title=m.tipo==="Hino"?`${m.hinario} ${m.numero} ${m.titulo}`:m.titulo; return `${title}${r.tom?` ${r.tom}`:""}${link&&m.youtube?`: ${m.youtube}`:""}`; }
function cleanLines(lines){ const out=[]; for(const x of lines){ if(x===""&&(!out.length||out.at(-1)==="")) continue; if(x!=="") out.push(x); else out.push(""); } while(out.at(-1)==="") out.pop(); return out; }
async function copy(text){ try{await navigator.clipboard.writeText(text);}catch{const t=document.createElement("textarea");t.value=text;t.style.position="fixed";t.style.opacity="0";document.body.append(t);t.select();document.execCommand("copy");t.remove();} toast("Copiado para a área de transferência"); }
function buildLinks(s){ return s.repertorio.flatMap(r=>{const m=music(r.musicaId); if(!m)return[]; const links=[["Cifra",m.cifra],["VS",m.vs]].filter(x=>x[1]).map(([l,u])=>`${l}: ${u}`); return links.length?[`${m.titulo} (${r.tom||'sem tom'})`,...links,""]:[];}).join("\n").trim()||"Nenhum link de cifra ou VS cadastrado."; }
function downloadResource(value,name){const url=safeUrl(value);if(!url){toast("Link inválido ou inseguro");return}try{const a=document.createElement("a");a.href=url;a.download=name;a.target="_blank";a.rel="noopener noreferrer";document.body.append(a);a.click();a.remove();toast(`Abrindo ${name.endsWith('.mp3')?'VS MP3':'cifra/letra PDF'}…`)}catch{window.open(url,"_blank","noopener,noreferrer");toast("O arquivo foi aberto em outra aba")}}
function downloadCsv(s){ const rows=[["Equipe"],["Função","Nome","WhatsApp"],...s.equipe.map(e=>[e.funcao,member(e.id)?.nome||"",member(e.id)?.whatsapp||""]),[],["Repertório"],["Momento","Música","Tom","Referência","Cifra","VS"],...s.repertorio.map(r=>{const m=music(r.musicaId)||{};return[r.momento,m.titulo||"",r.tom||"",m.youtube||"",m.cifra||"",m.vs||""]})]; const csv="\ufeff"+rows.map(row=>row.map(x=>`"${String(x).replaceAll('"','""')}"`).join(";")).join("\r\n"); try{const url=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download=`escala-${s.data}.csv`;a.click();URL.revokeObjectURL(url);toast("Planilha baixada");}catch{copy(csv);toast("Download bloqueado — CSV copiado");} }

function newScale(date=iso(new Date())){ const wed=parseDate(date).getDay()===3; state.editingScale={id:uid(),data:date,culto:wed?CULTOS[1]:CULTOS[0],saudacao:"Olá!",ensaio:wed?"":"Ensaio no domingo após a EBD.",obs:"",equipe:[],repertorio:[],__new:true}; state.screen="editor"; state.drawer=false; render(); }
function duplicate(id){ const src=state.db.escalas.find(e=>e.id===id); if(!src)return; const d=new Date(parseDate(src.data)); d.setDate(d.getDate()+7); state.editingScale=structuredClone(src); state.editingScale.id=uid();state.editingScale.data=iso(d);state.editingScale.__new=true;state.screen="editor";render(); }
async function toggleCandidate(id){ const editing=Boolean(state.editingScale),s=state.editingScale||activeScale(),before=structuredClone(s.equipe),f=state.sheet; const idx=s.equipe.findIndex(e=>e.id===id&&e.funcao===f); if(idx>=0)s.equipe.splice(idx,1);else { const limit=VOCAL_LIMITS[f]; if(limit&&s.equipe.filter(e=>e.funcao===f).length>=limit){toast(`Limite de ${limit} vagas para ${f.toLowerCase()}`);return;} s.equipe.push({id,funcao:f}); } if(!editing&&supabase&&!await persist(()=>syncScale(s),"Equipe atualizada"))s.equipe=before;else if(!editing)save();render(); }

function preserveSongDraft(form){
  if(!form||state.modal?.type!=="song")return;
  state.modal.item={...state.modal.item,...Object.fromEntries(new FormData(form))};
}
async function storageLogin(button){
  if(!supabase)return;
  const panel=button.closest(".storage-panel"), form=button.closest("form");
  const email=$('[data-storage-email]',panel)?.value.trim(), password=$('[data-storage-password]',panel)?.value;
  const status=$('[data-storage-auth-status]',panel);
  if(!email||!password){status.textContent="Informe e-mail e senha.";return}
  button.disabled=true;status.textContent="Entrando…";
  try{const {data,error}=await supabase.auth.signInWithPassword({email,password});if(error)throw error;preserveSongDraft(form);state.storageSession=data.session;render();toast("Supabase conectado")}catch(error){button.disabled=false;status.textContent=`Não foi possível entrar: ${error?.message||"verifique sua conexão"}`}
}
async function storageLogout(button){
  if(!supabase)return;
  preserveSongDraft(button.closest("form"));
  try{await supabase.auth.signOut()}finally{state.storageSession=null;render();toast("Conta desconectada")}
}
function safeFilePart(value){return String(value||"arquivo").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"").slice(0,60)||"arquivo"}
async function uploadStorageFile(input){
  const kind=input.dataset.storageFile, file=input.files?.[0], form=input.closest("form");
  if(!file||!supabase||!state.storageSession)return;
  const isPdf=kind==="pdf", ext=isPdf?"pdf":"mp3", max=isPdf?15:50;
  const valid=isPdf?(file.type==="application/pdf"||/\.pdf$/i.test(file.name)):(["audio/mpeg","audio/mp3"].includes(file.type)||/\.mp3$/i.test(file.name));
  const status=$(`[data-upload-status="${kind}"]`,form), box=input.closest(".upload-box");
  if(!valid){status.textContent=`Escolha um arquivo ${ext.toUpperCase()}.`;input.value="";return}
  if(file.size>max*1024*1024){status.textContent=`O limite é ${max} MB.`;input.value="";return}
  const title=form.elements.titulo.value||file.name.replace(/\.[^.]+$/,"");
  const path=`${isPdf?"cifras":"vs"}/${safeFilePart(title)}-${Date.now()}-${uid()}.${ext}`;
  box.classList.remove("success");box.classList.add("uploading");status.textContent=`Enviando ${file.name}…`;
  try{const {data,error}=await supabase.storage.from(SUPABASE_BUCKET).upload(path,file,{cacheControl:"3600",contentType:isPdf?"application/pdf":"audio/mpeg",upsert:false});if(error)throw error;const {data:publicFile}=supabase.storage.from(SUPABASE_BUCKET).getPublicUrl(data.path);form.elements[isPdf?"cifra":"vs"].value=publicFile.publicUrl;box.classList.add("success");status.textContent=`${file.name} enviado ✓`;toast(`${ext.toUpperCase()} enviado e link preenchido`)}catch(error){status.textContent=`Falha no envio: ${error?.message||"verifique sua conexão"}`;toast("Não foi possível enviar o arquivo")}finally{box.classList.remove("uploading")}
}

function assertCloud(result){if(result?.error)throw result.error;return result}
async function syncMember(item){
  if(!supabase||!state.storageSession)return;
  assertCloud(await supabase.from("membros").upsert({id:item.id,nome:item.nome,whatsapp:item.whatsapp||"",avatar:item.avatar||{},ativo:true},{onConflict:"id"}));
  assertCloud(await supabase.from("membro_funcoes").delete().eq("membro_id",item.id));
  if(item.funcoes.length)assertCloud(await supabase.from("membro_funcoes").insert(item.funcoes.map((funcao,ordem)=>({membro_id:item.id,funcao,ordem}))));
}
async function syncSong(item){
  if(!supabase||!state.storageSession)return;
  assertCloud(await supabase.from("musicas").upsert({id:item.id,tipo:item.tipo||"Música",hinario:item.hinario||"",numero:item.numero||"",titulo:item.titulo,tom_padrao:item.tom||"",youtube_url:item.youtube||"",cifra_url:item.cifra||"",vs_url:item.vs||"",ativo:true},{onConflict:"id"}));
}
async function syncScale(scale){
  if(!supabase||!state.storageSession)return;
  assertCloud(await supabase.from("escalas").upsert({id:scale.id,data:scale.data,culto:scale.culto,saudacao:scale.saudacao||"Olá!",ensaio:scale.ensaio||"",observacoes:scale.obs||""},{onConflict:"id"}));
  assertCloud(await supabase.from("escala_equipe").delete().eq("escala_id",scale.id));
  if(scale.equipe.length)assertCloud(await supabase.from("escala_equipe").insert(scale.equipe.map((item,ordem)=>({escala_id:scale.id,membro_id:item.id,funcao:item.funcao,ordem}))));
  assertCloud(await supabase.from("escala_repertorio").delete().eq("escala_id",scale.id));
  if(scale.repertorio.length)assertCloud(await supabase.from("escala_repertorio").insert(scale.repertorio.map((item,ordem)=>({id:item.chave,escala_id:scale.id,musica_id:item.musicaId,tom:item.tom||"",momento:item.momento||"Louvor",ordem}))));
}
async function deleteCloudScale(id){if(supabase&&state.storageSession)assertCloud(await supabase.from("escalas").delete().eq("id",id))}
async function persist(action,successMessage){
  state.syncing=true;
  try{await action();save();if(successMessage)toast(successMessage);return true}
  catch(error){toast(`Erro ao sincronizar: ${error?.message||"verifique a conexão"}`);return false}
  finally{state.syncing=false}
}

function bind(){
  $$('[data-action="leader-login"]').forEach(b=>b.onclick=requestLeaderAccess);
  $$('[data-nav]').forEach(b=>b.onclick=()=>navigate(b.dataset.nav));
  $$('[data-action="drawer"]').forEach(b=>b.onclick=()=>{state.drawer=true;render()});
  $$('[data-action="close-drawer"]').forEach(b=>b.onclick=()=>{state.drawer=false;render()});
  $$('[data-menu]').forEach(b=>b.onclick=()=>menuAction(b.dataset.menu));
  $('[data-action="select-scale"]')?.addEventListener('change',e=>{state.selected=e.target.value;state.calendarDate=parseDate(activeScale().data);render()});
  $('[data-action="calendar"]')?.addEventListener('click',()=>{state.calendar=!state.calendar;render()});
  $$('[data-cal]').forEach(b=>b.onclick=()=>{state.calendarDate=new Date(state.calendarDate.getFullYear(),state.calendarDate.getMonth()+(b.dataset.cal==='next'?1:-1),1);render()});
  $$('[data-day]').forEach(b=>b.onclick=()=>{const found=state.db.escalas.find(e=>e.data===b.dataset.day);if(found){state.selected=found.id;render()}else newScale(b.dataset.day)});
  $$('[data-position]').forEach(b=>b.onclick=()=>{state.sheet=b.dataset.position;render()});
  $$('[data-action="close-sheet"]').forEach(b=>b.onclick=()=>{state.sheet=null;render()});
  $$('[data-candidate]').forEach(b=>b.onclick=()=>toggleCandidate(b.dataset.candidate));
  $$('[data-action="message"]').forEach(b=>b.onclick=()=>window.open(`https://wa.me/?text=${encodeURIComponent(buildMessage(activeScale()))}`,"_blank","noopener,noreferrer"));
  $$('[data-action="copy"]').forEach(b=>b.onclick=()=>copy(buildMessage(activeScale())));
  $$('[data-action="links"]').forEach(b=>b.onclick=()=>copy(buildLinks(activeScale())));
  $$('[data-action="csv"]').forEach(b=>b.onclick=()=>downloadCsv(activeScale()));
  $$('[data-copy-id]').forEach(b=>b.onclick=()=>copy(buildMessage(state.db.escalas.find(e=>e.id===b.dataset.copyId))));
  $$('[data-open-id]').forEach(b=>b.onclick=()=>{state.selected=b.dataset.openId;navigate('escala')});
  $$('[data-duplicate]').forEach(b=>b.onclick=()=>duplicate(b.dataset.duplicate));
  $$('[data-delete-scale]').forEach(b=>b.onclick=async()=>{if(!confirm("Excluir esta escala?"))return;const id=b.dataset.deleteScale;if(supabase&&!await persist(()=>deleteCloudScale(id)))return;state.db.escalas=state.db.escalas.filter(e=>e.id!==id);state.selected=nearestScale()?.id;save();render();toast("Escala excluída")});
  $$('[data-action="new-scale"]').forEach(b=>b.onclick=()=>newScale());
  $('[data-search]')?.addEventListener('input',e=>{const p=e.target.selectionStart;state.query=e.target.value;render();const n=$('[data-search]');n.focus();n.setSelectionRange(p,p)});
  $$('[data-action="new-member"]').forEach(b=>b.onclick=()=>{state.modal={type:'member',item:{funcoes:[]}};render()});
  $$('[data-edit-member]').forEach(b=>b.onclick=()=>{state.modal={type:'member',item:structuredClone(member(b.dataset.editMember))};render()});
  $$('[data-action="new-song"]').forEach(b=>b.onclick=()=>{state.modal={type:'song',item:{tipo:'Música'}};render()});
  $$('[data-download-url]').forEach(b=>b.onclick=e=>{e.stopPropagation();downloadResource(b.dataset.downloadUrl,b.dataset.downloadName)});
  $$('[data-play-url]').forEach(b=>b.onclick=e=>{e.stopPropagation();state.audio={url:b.dataset.playUrl,title:b.dataset.playTitle};render()});
  $('[data-action="close-audio"]')?.addEventListener('click',()=>{state.audio=null;render()});
  $$('[data-edit-song]').forEach(b=>b.onclick=()=>{state.modal={type:'song',item:structuredClone(music(b.dataset.editSong))};render()});
  $$('[data-action="close-modal"]').forEach(b=>b.onclick=()=>{state.modal=null;render()});
  $$('[data-form-function]').forEach(b=>b.onclick=()=>b.classList.toggle('selected'));
  $$('[data-form]').forEach(f=>f.onsubmit=e=>saveForm(e,f));
  $('[data-storage-login]')?.addEventListener('click',e=>storageLogin(e.currentTarget));
  $('[data-storage-logout]')?.addEventListener('click',e=>storageLogout(e.currentTarget));
  $$('[data-storage-file]').forEach(input=>input.onchange=()=>uploadStorageFile(input));
  $$('[name^="avatar"]').forEach(i=>{i.oninput=refreshAvatarPreview;i.onchange=refreshAvatarPreview});
  refreshAvatarPreview();
  $$('[data-editor-mode]').forEach(b=>b.onclick=()=>{state.editorMode=b.dataset.editorMode;render()});
  $$('[data-scale-field]').forEach(i=>{i.oninput=()=>{(state.editingScale||activeScale())[i.dataset.scaleField]=i.value};i.onchange=()=>{(state.editingScale||activeScale())[i.dataset.scaleField]=i.value;if(i.type==='date'||i.tagName==='SELECT')render()}});
  $$('[data-song-key]').forEach(i=>i.oninput=()=>{const r=(state.editingScale||activeScale()).repertorio.find(r=>r.chave===i.dataset.songKey);if(r)r.tom=i.value});
  $$('[data-song-moment]').forEach(i=>i.onchange=()=>{const r=(state.editingScale||activeScale()).repertorio.find(r=>r.chave===i.dataset.songMoment);r.momento=i.value;render()});
  $$('[data-move-song]').forEach(b=>b.onclick=()=>moveSong(b.dataset.moveSong,+b.dataset.dir));
  $$('[data-remove-song]').forEach(b=>b.onclick=()=>{const s=state.editingScale||activeScale();s.repertorio=s.repertorio.filter(r=>r.chave!==b.dataset.removeSong);render()});
  $('[data-action="add-editor-song"]')?.addEventListener('click',()=>{state.modal={type:'song-picker'};render()});
  $$('[data-pick-song]').forEach(b=>b.onclick=()=>{const s=state.editingScale||activeScale(),m=music(b.dataset.pickSong);if(!m||s.repertorio.some(r=>r.musicaId===m.id)){toast("Esta música já está na escala");return}s.repertorio.push({chave:uid(),musicaId:m.id,tom:m.tom||'',momento:'Louvor'});state.modal=null;render();toast("Música adicionada")});
  $('[data-picker-search]')?.addEventListener('input',e=>{const q=e.target.value.toLocaleLowerCase('pt-BR');$$('[data-song-candidate]').forEach(row=>{const m=music(row.dataset.songCandidate);row.hidden=!`${m?.titulo||''} ${m?.hinario||''} ${m?.numero||''}`.toLocaleLowerCase('pt-BR').includes(q)})});
  $('[data-action="save-scale"]')?.addEventListener('click',saveScale);
  $$('[data-action="cancel-scale"]').forEach(b=>b.onclick=()=>{if(confirm("Descartar as alterações desta escala?")){state.editingScale=null;state.screen='escala';render()}});
  $('[data-action="copy-editor"]')?.addEventListener('click',()=>copy(buildMessage(state.editingScale||activeScale())));
  $('[data-action="reset"]')?.addEventListener('click',()=>{if(confirm("Restaurar os dados originais? Alterações locais serão perdidas.")){localStorage.removeItem(STORAGE);location.reload()}});
  $('[data-action="reload-cloud"]')?.addEventListener('click',async()=>{state.drawer=false;toast("Atualizando dados…");if(await loadCloudData()){state.selected=state.db.escalas.some(s=>s.id===state.selected)?state.selected:nearestScale()?.id;render();toast("Dados atualizados")}else render()});
  $('[data-action="logout"]')?.addEventListener('click',appLogout);
}
function menuAction(a){ state.drawer=false; if(["escala","agenda","repertorio","equipe"].includes(a))navigate(a); else if(a==='new-scale')newScale();else if(a==='new-member'){state.screen='equipe';state.modal={type:'member',item:{funcoes:[]}};render()}else if(a==='editor'||a==='editor-music'){state.editingScale=structuredClone(activeScale());state.screen='editor';render()}else if(a==='message')window.open(`https://wa.me/?text=${encodeURIComponent(buildMessage(activeScale()))}`,"_blank","noopener,noreferrer");else if(a==='csv')downloadCsv(activeScale());else if(a==='links')copy(buildLinks(activeScale())); }
async function saveForm(e,f){e.preventDefault();const submit=$('button[type="submit"],button:not([type])',f),fd=new FormData(f),type=f.dataset.form;submit.disabled=true;submit.textContent="Salvando…";if(type==='member'){const item={id:fd.get('id')||uid(),nome:String(fd.get('nome')||'').trim(),whatsapp:String(fd.get('whatsapp')||'').trim(),avatar:{tipo:fd.get('avatarTipo'),estilo:fd.get('avatarEstilo'),pele:fd.get('avatarPele'),cabelo:fd.get('avatarCabelo')},funcoes:$$('[data-form-function].selected',f).map(b=>b.dataset.formFunction)};if(!item.nome){toast("Informe o nome do membro");submit.disabled=false;submit.textContent="Salvar";return}if(supabase&&!await persist(()=>syncMember(item))){submit.disabled=false;submit.textContent="Salvar";return}const i=state.db.membros.findIndex(x=>x.id===item.id);i>=0?state.db.membros[i]=item:state.db.membros.push(item);}else{const item=Object.fromEntries(fd);Object.keys(item).forEach(k=>{if(typeof item[k]==='string')item[k]=item[k].trim()});if(!item.titulo){toast("Informe o título da música");submit.disabled=false;submit.textContent="Salvar";return}item.id||=uid();if(supabase&&!await persist(()=>syncSong(item))){submit.disabled=false;submit.textContent="Salvar";return}const i=state.db.musicas.findIndex(x=>x.id===item.id);i>=0?state.db.musicas[i]=item:state.db.musicas.push(item);}save();state.modal=null;render();toast("Cadastro sincronizado");}
function moveSong(key,dir){const s=state.editingScale||activeScale(),i=s.repertorio.findIndex(r=>r.chave===key),j=i+dir;if(j<0||j>=s.repertorio.length)return;[s.repertorio[i],s.repertorio[j]]=[s.repertorio[j],s.repertorio[i]];render();}
async function saveScale(){const s=state.editingScale;if(!s)return;if(!s.data||!s.culto){toast("Informe a data e o culto");return}if(supabase&&!await persist(()=>syncScale(s)))return;delete s.__new;const i=state.db.escalas.findIndex(e=>e.id===s.id);i>=0?state.db.escalas[i]=s:state.db.escalas.push(s);state.db.escalas.sort((a,b)=>a.data.localeCompare(b.data));state.selected=s.id;if(!save())return;state.editingScale=null;state.screen='escala';render();toast("Escala sincronizada");}

init();
